#!/bin/bash

set -e

if [ "$(uname)" = "Linux" ]; then
    PREFIX="/usr"
elif [ "$(uname)" = "FreeBSD" ]; then
    PREFIX="/usr/local"
fi

engine_name="lotus"
engine_gui_name="ibus-setup-Lotus.desktop"
ibus_e_name="ibus-engine-${engine_name}"
pkg_name="ibus-${engine_name}"
version="1.0.2"

engine_dir=${PREFIX}/share/${pkg_name}
ibus_dir=${PREFIX}/share/ibus

# Main script
case $(uname) in
	"Linux") mkdir -p ${DESTDIR}${engine_dir} \
		${DESTDIR}${PREFIX}/lib/ibus-${engine_name} \
		${DESTDIR}${ibus_dir}/component/ \
		${DESTDIR}${PREFIX}/share/applications/
		cp -R -f icons data ${DESTDIR}${engine_dir}
		echo "Copying icons and data folder to ${engine_dir}"
		cp -f ${ibus_e_name} ${DESTDIR}${PREFIX}/lib/ibus-${engine_name}/
		echo "Copying executable to ${DESTDIR}${PREFIX}/lib/ibus-${engine_name}"
		cp -f data/${engine_name}.xml ${DESTDIR}${ibus_dir}/component/
		echo "Copying ibus component XML to ${DESTDIR}${ibus_dir}/component/"
		cp -f data/${engine_gui_name} ${DESTDIR}${PREFIX}/share/applications/
		echo "Copying desktop file to ${DESTDIR}${PREFIX}/share/applications/"
		echo "---"
		echo "Ibus Lotus successfully installed! You may need to restart your desktop environment session to take effect"
		echo "You can delete the current folder to save storage"
		;;
	"FreeBSD") mkdir -p ${DESTDIR}${engine_dir} \
		${DESTDIR}${PREFIX}/lib/ibus-${engine_name} \
		${DESTDIR}${ibus_dir}/component/ \
		${DESTDIR}${PREFIX}/share/applications/

		cp -R -f icons data ${DESTDIR}${engine_dir}
		echo "Copying icons and data folder to ${DESTDIR}${engine_dir}"
		cp -f ${ibus_e_name} ${DESTDIR}${PREFIX}/lib/ibus-${engine_name}/
		echo "Copying executable to ${DESTDIR}${PREFIX}/lib/ibus-${engine_name}"
		cp -f data/${engine_name}-freebsd.xml ${DESTDIR}${ibus_dir}/component/
		echo "Copying ibus component XML to ${DESTDIR}${ibus_dir}/component/"
		cp -f data/${engine_gui_name} ${DESTDIR}${PREFIX}/share/applications/
		echo "Copying desktop file to ${DESTDIR}${PREFIX}/share/applications/"
		echo "---"
		echo "Ibus Lotus successfully installed! You may need to restart your desktop environment session to take effect"
		echo "You can delete the current folder to save storage"
		;;
	*)	echo "Error: Unknown operating system"
		;;
esac
